/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instaaid;

import java.awt.Color;

/**
 *
 * @author User
 */
public class EmailForm extends javax.swing.JFrame {

    /**
     * Creates new form EmailForm
     */
    String receiverAddress, relation, situation, hospitalName, nickname;
    public EmailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InstaAid");
        setLocation(new java.awt.Point(200, 30));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel1.setBackground(new java.awt.Color(135, 206, 250));
        jPanel1.setLayout(null);

        tf5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf5.setForeground(new java.awt.Color(204, 204, 204));
        tf5.setText("i.e. broke leg");
        tf5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf5FocusGained(evt);
            }
        });
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        tf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf5KeyReleased(evt);
            }
        });
        jPanel1.add(tf5);
        tf5.setBounds(500, 320, 430, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Who are you to the person? : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 440, 330, 30);

        tf3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf3.setForeground(new java.awt.Color(204, 204, 204));
        tf3.setText("i.e. brother");
        tf3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf3FocusGained(evt);
            }
        });
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf3KeyReleased(evt);
            }
        });
        jPanel1.add(tf3);
        tf3.setBounds(500, 440, 430, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("What is your emergency? :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 310, 350, 50);

        tf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf1.setText(".com");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1);
        tf1.setBounds(500, 260, 430, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email Address of the person : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 250, 370, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Which hospital will you be at? :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 370, 320, 50);

        tf6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf6.setForeground(new java.awt.Color(204, 204, 204));
        tf6.setText("i.e. BRB Cables Hospital, Dhanmondi");
        tf6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf6FocusGained(evt);
            }
        });
        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        tf6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf6KeyReleased(evt);
            }
        });
        jPanel1.add(tf6);
        tf6.setBounds(500, 380, 430, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Which name does he/she call you by? :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 490, 353, 50);

        tf4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf4.setForeground(new java.awt.Color(204, 204, 204));
        tf4.setText("i.e. James");
        tf4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf4FocusGained(evt);
            }
        });
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        tf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf4KeyReleased(evt);
            }
        });
        jPanel1.add(tf4);
        tf4.setBounds(500, 500, 430, 40);

        b3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instaaid/Back-Arrow-Icon-PNG-715x715.png"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(20, 20, 50, 40);

        b1.setBackground(new java.awt.Color(255, 0, 0));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("Send ");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(660, 580, 120, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("It's always better to let someone close know that you are in an emergency !   ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-170, 90, 1190, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("They might be able to help!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 130, 690, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instaaid/doctor5.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
       
    }//GEN-LAST:event_tf5ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        
    }//GEN-LAST:event_tf6ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed

    }//GEN-LAST:event_tf4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

    new ChooseEmergencies().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_b3ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed

    }//GEN-LAST:event_tf3ActionPerformed

    private void tf3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyPressed
        if(tf3.getForeground()!=Color.BLACK)
        {
            if(tf3.getText().equals("i.e. brother"))
            {
                tf3.setText("");
            }
        }
        tf3.setForeground(Color.BLACK);
    }//GEN-LAST:event_tf3KeyPressed

    private void tf3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf3FocusGained
        tf3.setCaretPosition(0);
    }//GEN-LAST:event_tf3FocusGained

    private void tf3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyReleased
        if(tf3.getText().isEmpty() == true)
        {
            tf3.setText("i.e. brother");
            tf3.setCaretPosition(0);
            tf3.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_tf3KeyReleased

    private void tf4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyPressed
        if(tf4.getForeground()!=Color.BLACK)
        {
            if(tf4.getText().equals("i.e. James"))
            {
                tf4.setText("");
            }
        }
        tf4.setForeground(Color.BLACK);
    }//GEN-LAST:event_tf4KeyPressed

    private void tf4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf4FocusGained
        tf4.setCaretPosition(0);
    }//GEN-LAST:event_tf4FocusGained

    private void tf4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyReleased
        if(tf4.getText().isEmpty() == true)
        {
            tf4.setText("i.e. James");
            tf4.setCaretPosition(0);
            tf4.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_tf4KeyReleased

    private void tf5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyPressed
        if(tf5.getForeground()!=Color.BLACK)
        {
            if(tf5.getText().equals("i.e. broke leg"))
            {
                tf5.setText("");
            }
        }
        tf5.setForeground(Color.BLACK);
    }//GEN-LAST:event_tf5KeyPressed

    private void tf5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf5FocusGained
        tf5.setCaretPosition(0);
    }//GEN-LAST:event_tf5FocusGained

    private void tf5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyReleased
        if(tf5.getText().isEmpty() == true)
        {
            tf5.setText("i.e. broke leg");
            tf5.setCaretPosition(0);
            tf5.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_tf5KeyReleased

    private void tf6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyPressed
        if(tf6.getForeground()!=Color.BLACK)
        {
            if(tf6.getText().equals("i.e. BRB Cables Hospital, Dhanmondi"))
            {
                tf6.setText("");
            }
        }
        tf6.setForeground(Color.BLACK);
    }//GEN-LAST:event_tf6KeyPressed

    private void tf6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf6FocusGained
        tf6.setCaretPosition(0);
    }//GEN-LAST:event_tf6FocusGained

    private void tf6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyReleased
        if(tf6.getText().isEmpty() == true)
        {
            tf6.setText("i.e. BRB Cables Hospital, Dhanmondi");
            tf6.setCaretPosition(0);
            tf6.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_tf6KeyReleased

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        receiverAddress = tf1.getText();
        relation = tf3.getText();
        nickname = tf4.getText();
        situation = tf5.getText();
        hospitalName = tf6.getText();
        String message = "Dear,\n\nYour " + relation + ", " + nickname + " is suffering from " + situation +  " and is currently at " + hospitalName + ". Please, meet there as soon as possible.\n\n - Team InstaAid";
        Notify.send(receiverAddress, nickname + " in emergency : " + situation, message, "insta.aid.team@gmail.com", "e%y4tZo7");
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    // End of variables declaration//GEN-END:variables
}
