/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instaaid;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        rfPasswordTextField.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        registrationFormLabel = new javax.swing.JLabel();
        rfUsernameLabel = new javax.swing.JLabel();
        rfUsernameTextField = new javax.swing.JTextField();
        rfPasswordLabel = new javax.swing.JLabel();
        rfPasswordTextField = new javax.swing.JPasswordField();
        rfDoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InstaAid");
        setLocation(new java.awt.Point(200, 30));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instaaid/doctor2.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-10, 0, 540, 660);

        jPanel1.setBackground(new java.awt.Color(135, 206, 250));

        registrationFormLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        registrationFormLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrationFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationFormLabel.setText("Create Account");

        rfUsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rfUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        rfUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rfUsernameLabel.setText("Username : ");

        rfUsernameTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rfUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfUsernameTextFieldActionPerformed(evt);
            }
        });

        rfPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rfPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        rfPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rfPasswordLabel.setText("Password : ");

        rfPasswordTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rfPasswordTextField.setText("jPasswordField1");
        rfPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfPasswordTextFieldActionPerformed(evt);
            }
        });

        rfDoneButton.setBackground(new java.awt.Color(0, 0, 153));
        rfDoneButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rfDoneButton.setForeground(new java.awt.Color(255, 255, 255));
        rfDoneButton.setText("Continue");
        rfDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfDoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rfUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rfPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrationFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(registrationFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rfUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rfPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(rfDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(530, 0, 710, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void rfDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfDoneButtonActionPerformed
        String storedUsername = null, storedPassword = null;
        try
        {
            FileWriter fw1 = new FileWriter("username.txt");
            BufferedWriter bw1 = new BufferedWriter(fw1);
            storedUsername = rfUsernameTextField.getText();
            bw1.write(storedUsername);
            bw1.close();
            FileWriter fw2 = new FileWriter("password.txt");
            BufferedWriter bw2 = new BufferedWriter(fw2);
            storedPassword = new String(rfPasswordTextField.getPassword());
            bw2.write(storedPassword);
            bw2.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
        homeframe hf=new homeframe();
        hf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rfDoneButtonActionPerformed
    */
    private void rfDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
            String storedUsername = rfUsernameTextField.getText();
            String storedPassword = new String(rfPasswordTextField.getPassword());
            PreparedStatement ps;/*A prepared statement or a parameterized statement is used to execute the same statement repeatedly with high efficiency*/
            ResultSet rs;/*A ResultSet object is a table of data representing a database result set, which is usually generated by executing a statement that queries the database.*/
            String registerUserQuery=("INSERT INTO `users`(`username`, `password`, `Height`, `Weight`, `BloodGroup`, `SugarLevel`, `BloodPressure`) VALUES (?, ?, ?, ?, ?, ?, ?)");
            try{
                ps=database1.getConnection().prepareStatement(registerUserQuery);
                ps.setString(1, storedUsername);
                ps.setString(2, storedPassword);
                ps.setString(3, null);
                ps.setString(4, null);
                ps.setString(5, null);
                ps.setString(6, null);
                ps.setString(7, null);
                
                int result=ps.executeUpdate();/*executeUpdate. Executes the given SQL statement, which may be an INSERT , UPDATE , or DELETE statement or an SQL statement */
            }catch(SQLException ex)
            {
                Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE,null,ex);            
            }
       this.dispose();
        new getstartedframe().setVisible(true);
    }   
    private void rfUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfUsernameTextFieldActionPerformed

    private void rfPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfPasswordTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrationForm rf=new RegistrationForm();
                rf.setVisible(false);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel registrationFormLabel;
    private javax.swing.JButton rfDoneButton;
    private javax.swing.JLabel rfPasswordLabel;
    private javax.swing.JPasswordField rfPasswordTextField;
    private javax.swing.JLabel rfUsernameLabel;
    private javax.swing.JTextField rfUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
